version: "0.1"

services:
  db:
    image: postgres:16-alpine
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: homework
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
  minio:
    image: minio/minio
    command: server --console-address ":${MINIO_WEB_PORT}" /data
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_WEB_PORT}:${MINIO_WEB_PORT}"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  redis:
    image: redis:alpine3.16
    container_name: redis-wsbe
    env_file: .env
    command: >
      --requirepass ${REDIS_PASSWORD} --port 6379
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
  minio_storage:
